# Cloudflare Pages configuration
name = "dashboard-eletrize"
compatibility_date = "2024-03-01"
pages_build_output_dir = "."

# VariÃ¡veis de ambiente devem ser configuradas no painel do Cloudflare Pages:
# Settings > Environment variables
# 
# HUBITAT_BASE_URL = https://cloud.hubitat.com/api/e45cb756-9028-44c2-8a00-e6fb3651856c/apps/172/devices
# HUBITAT_ACCESS_TOKEN = beddf703-c860-47bf-a6df-3df6ccc98138